# Site settings
baseurl: ''
url: 'http://rezvanov.info'
title: Замкнутость и созерцание - Rezvanov.info
description: Программист, энтузиаст, геймер.

# Build settings
markdown: kramdown

# Required gems
gems: [i18n]
