# Site settings
baseurl: ''
url: 'http://rezvanov.info'
title: Замкнутость и созерцание - rezvanov.info
description: Ruby/Go энтузиаст, DevOps.

# Build settings
markdown: kramdown

# Required gems
gems: [i18n]
